services:
    - name: authService
      port: 8000
      proxyPort: 5000
    - name: dashboardService
      port: 8001
      proxyPort: 5001
    - name: profileService
      port: 8002
      proxyPort: 5002  


mesh:
  mTLS: enabled
  logging: enabled
  allowedCalls:
    - from: authService
      to: dashboardService   
    - from: dashboardService
      to: profileService  

